project:
  type: website

website:
  title: "Algoverse"
  navbar:
    right:
      - about.qmd
      - icon: twitter
        href: https://twitter.com/WardsBen
      - icon: linkedin
        href: https://www.linkedin.com/in/ben-wards-014a8282
      - icon: github
        href: https://github.com/benwardswards
      - icon: mastodon
        href: https://techhub.social/@bdwards
format:
  html:
    theme: theme.scss
    css: styles.css
site-url: https://github.com/benwardswards
